### ISSUE TITLE
Only 5 bots joining

### ISSUE THREAD

**Issue by RiskiiYo** [peter12908/PeterBOT#13]
Hello i have looked through lots of different posts on this github and none of them are working.
Only 5 bots are joining the server when i have selected 100 and i have 1k bot names as a txt and the server slots are at 200.

**Comment by peter12908** [comment]
please post the output of bot console

**Comment by RiskiiYo** [comment]
--- Bot[1] ---
Bot[1] ready
Bot[1] trying to connect to petertest.feathermc.gg:25565
Bot[1] loggin in...
Bot[1] successfully connected!



--- Bot[2] ---
Bot[2] ready
Bot[2] trying to connect to petertest.feathermc.gg:25565
Bot[2] loggin in...
Bot[2] successfully connected!



--- Bot[3] ---
Bot[3] ready
Bot[3] trying to connect to petertest.feathermc.gg:25565
Bot[3] loggin in...
Bot[3] successfully connected!
Bot[3] died.



--- Bot[4] ---
Bot[4] ready
Bot[4] trying to connect to petertest.feathermc.gg:25565
Bot[4] loggin in...
Bot[4] successfully connected!



--- Bot[5] ---
Bot[5] ready
Bot[5] trying to connect to petertest.feathermc.gg:25565
Bot[5] loggin in...
Bot[5] successfully connected!



--- Bot[6] ---
Bot[6] ready
Bot[6] trying to connect to petertest.feathermc.gg:25565
Bot[6] an Error occured, Error: connect ETIMEDOUT 185.187.154.117:25565
Bot[6] connection closed.



--- Bot[7] ---
Bot[7] ready
Bot[7] trying to connect to petertest.feathermc.gg:25565
Bot[7] an Error occured, Error: connect ETIMEDOUT 185.187.154.117:25565
Bot[7] connection closed.



--- Bot[8] ---
Bot[8] ready
Bot[8] trying to connect to petertest.feathermc.gg:25565
Bot[8] an Error occured, Error: connect ETIMEDOUT 185.187.154.117:25565
Bot[8] connection closed.



--- Bot[9] ---
Bot[9] ready
Bot[9] trying to connect to petertest.feathermc.gg:25565
Bot[9] an Error occured, Error: connect ETIMEDOUT 185.187.154.117:25565
Bot[9] connection closed.



--- Bot[10] ---
Bot[10] ready
Bot[10] trying to connect to petertest.feathermc.gg:25565

**Comment by peter12908** [comment]
seems like the server is denying the bots to join, do you have like a plugin which defines max amount of players per ip, or a firewall or something like that? if yes disable it.

**Comment by RiskiiYo** [comment]
i tried a different server host and it worked thanks for you help.
