### ISSUE TITLE
Help, pls

### ISSUE THREAD

**Issue by CrippinDog3** [peter12908/PeterBOT#14]
When i put more than 3 bot this happens:

--- Bot[Fuckedby_Crippin_lwu] ---
Bot[Fuckedby_Crippin_lwu] ready
Bot[Fuckedby_Crippin_lwu] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_lwu] connection closed.

--- Bot[Fuckedby_Crippin_car] ---
Bot[Fuckedby_Crippin_car] ready
Bot[Fuckedby_Crippin_car] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_car] connection closed.

--- Bot[Fuckedby_Crippin_toa] ---
Bot[Fuckedby_Crippin_toa] ready
Bot[Fuckedby_Crippin_toa] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_toa] connection closed.

--- Bot[Fuckedby_Crippin_kat] ---
Bot[Fuckedby_Crippin_kat] ready
Bot[Fuckedby_Crippin_kat] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_kat] connection closed.

--- Bot[Fuckedby_Crippin_lea] ---
Bot[Fuckedby_Crippin_lea] ready
Bot[Fuckedby_Crippin_lea] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_lea] connection closed.

--- Bot[Fuckedby_Crippin_lka] ---
Bot[Fuckedby_Crippin_lka] ready
Bot[Fuckedby_Crippin_lka] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_lka] connection closed.

--- Bot[Fuckedby_Crippin_jre] ---
Bot[Fuckedby_Crippin_jre] ready
Bot[Fuckedby_Crippin_jre] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_jre] connection closed.

--- Bot[Fuckedby_Crippin_jdk] ---
Bot[Fuckedby_Crippin_jdk] ready
Bot[Fuckedby_Crippin_jdk] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_jdk] connection closed.

--- Bot[Fuckedby_Crippin_jna] ---
Bot[Fuckedby_Crippin_jna] ready
Bot[Fuckedby_Crippin_jna] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_jna] connection closed.

--- Bot[Fuckedby_Crippin_aaj] ---
Bot[Fuckedby_Crippin_aaj] ready
Bot[Fuckedby_Crippin_aaj] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_aaj] connection closed.

--- Bot[Fuckedby_Crippin_on8] ---
Bot[Fuckedby_Crippin_on8] ready
Bot[Fuckedby_Crippin_on8] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_on8] connection closed.

--- Bot[Fuckedby_Crippin_egr] ---
Bot[Fuckedby_Crippin_egr] ready
Bot[Fuckedby_Crippin_egr] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_egr] connection closed.

--- Bot[Fuckedby_Crippin_rin] ---
Bot[Fuckedby_Crippin_rin] ready
Bot[Fuckedby_Crippin_rin] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_rin] connection closed.

--- Bot[Fuckedby_Crippin_muo] ---
Bot[Fuckedby_Crippin_muo] ready
Bot[Fuckedby_Crippin_muo] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_muo] connection closed.

--- Bot[Fuckedby_Crippin_aha] ---
Bot[Fuckedby_Crippin_aha] ready
Bot[Fuckedby_Crippin_aha] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_aha] connection closed.

--- Bot[Fuckedby_Crippin_tit] ---
Bot[Fuckedby_Crippin_tit] ready
Bot[Fuckedby_Crippin_tit] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_tit] connection closed.

--- Bot[Fuckedby_Crippin_ula] ---
Bot[Fuckedby_Crippin_ula] ready
Bot[Fuckedby_Crippin_ula] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_ula] connection closed.

--- Bot[Fuckedby_Crippin_inc] ---
Bot[Fuckedby_Crippin_inc] ready
Bot[Fuckedby_Crippin_inc] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_inc] connection closed.

--- Bot[Fuckedby_Crippin_tta] ---
Bot[Fuckedby_Crippin_tta] ready
Bot[Fuckedby_Crippin_tta] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_tta] connection closed.

--- Bot[Fuckedby_Crippin_cit] ---
Bot[Fuckedby_Crippin_cit] ready
Bot[Fuckedby_Crippin_cit] trying to connect to 127.0.0.1:25565
Bot[Fuckedby_Crippin_cit] connection closed.

**Comment by peter12908** [comment]
Try setting a delay for the bots to join, also post the output of minecraft server console.

**Comment by peter12908** [comment]
closed due to inactivity
