### ISSUE TITLE
bots are not joining

### ISSUE THREAD

**Issue by WiaderQ** [peter12908/PeterBOT#2]
bots are not joining or only one is joining

**Comment by peter12908** [comment]
Check if you set connection-throttle to 0 in the spigot.yml or set the delay to 5000 in PeterBot

**Comment by peter12908** [comment]
> 
> 
> Check if you set connection-throttle to 0 in the spigot.yml or set the delay to 5000 in PeterBot

sorry i meant the bukkit.yml
