### ISSUE TITLE
It just says trying to start instance and nothing happens

### ISSUE THREAD

**Issue by panmlg** [peter12908/PeterBOT#5]
When I try to join a 1.16.5 server, it just says trying to start instance and it does nothing.

**Comment by peter12908** [comment]
that is normal, the bot console is only usefull if you use macros, if you dont use macros the bot console isn't neccesairy

**Comment by panmlg** [comment]
But the bots never join.

**Comment by peter12908** [comment]
how many bots do you want to join? Are you using Proxys (if yes dont use them  [leave the field blank])? Which version are you using Auto Version or manuel 1.16.5? Did you try setting the Delay higher for example set it to 5000ms

**Comment by panmlg** [comment]
I tried to set it to 5000ms, I tried with and without proxys, I tried using Auto Version and manual. Nothing worked.

**Comment by panmlg** [comment]
I want 11 bots, but I tried with one.

**Comment by peter12908** [comment]
send a screenshot how you fill it into peterbot. Did you also check the correct port? and is the server online

**Comment by panmlg** [comment]
The server is 100% online and port is copy pasted in

**Comment by panmlg** [comment]
![image](https://user-images.githubusercontent.com/80635767/114178343-e50fba00-993d-11eb-9ece-7a7592721fb9.png)

**Comment by peter12908** [comment]
oh, yeah aternos server dont work for some weird reason

**Comment by panmlg** [comment]
Ok thanks.
