### ISSUE TITLE
add 1.19 support

### ISSUE THREAD

**Issue by CallumUncensored** [peter12908/PeterBOT#8]
Program is great, unfortunately just need that 1.19 support.

**Comment by peter12908** [comment]
unfortunatly mineflayer doesn't support version 1.19 yet. Once they add it, I will add it into PeterBot as soon as possible.

Link to mineflayer: https://github.com/PrismarineJS/mineflayer

**Comment by Phardeus** [comment]
Hey i dont know if you noticed mineflayer has updated to 1.19

**Comment by peter12908** [comment]
I actually have noticed, but unfortunatly during testing the results showed that only version 1.19.0 is supported an not 1.19.2, which the most servers run on. Therefore I am waiting for mineflayer to release version 1.19.2.

**Comment by peter12908** [comment]
added.
